# **Day 2 - Data Manipulation**

## Contents

- **Part 1 - Numpy (45 min)**
    - 1.0. Lists and Numpy
    - 1.1. 1D arrays
    - 1.2. 2D arrays
    - 1.3. Basic Statistic
- **Part 2 - Pandas (75 min)**
    - 2.1. Dataframes Methods and Attributes
    - 2.2. Import Data
    - 2.3. Explore Dataframes
    - 2.4. Dataframe groupby Method
    - 2.5. Dataframe: Filtering
    - 2.6. Dataframe: Slicing
    - 2.7. Sorting Dataframes
    - 2.8. Handling Missing Values
    - 2.9. Merge Dataframes
- **Test (15 min)**

# Import Python Libraries

**NumPy:** (https://numpy.org/)
- introduces objects for multidimensional arrays and matrices, as well as functions that allow to easily perform advanced mathematical and statistical operations on those objects.
- Provides vectorization of mathematical operations on arrays and matrices which significantly improves the performance
- many other python libraries are built on NumPy.

**Pandas:** (https://pandas.pydata.org/)
- Adds data structures and tools designed to work with table-like data.
- Provides tools for data manipulation: reshaping, merging, sorting, slicing, aggregation etc.
- Allows handling missing data.

**SQLAlchemy:** (https://www.sqlalchemy.org/)

In [1]:
import numpy as np  # import numpy library under the name or alias np
import pandas as pd  # import pandas library under the name or alias pd
from sqlalchemy import create_engine  # import a module of sqlalchemy library

# Part 1. Numpy

## 1.0 Lists and Numpy

Lists are:
- Collection of values
- Hold different types of data
- Can be changed, added or moved
- Used for basic mathematical operations and Data Science

In [2]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
print(height)
print(type(height))

[1.73, 1.68, 1.71, 1.89, 1.79]
<class 'list'>


In [3]:
weight = [65.4, 59.2,63.6, 88.4, 68.7]
print(weight)
print(type(weight))

[65.4, 59.2, 63.6, 88.4, 68.7]
<class 'list'>


### What is numpy?
NumPy is the fundamental package for scientific computing in Python. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

by using NumPy, a developer can perform the following operations:
- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation

Has the special features of:
- Can contain only a single data type
- Use less space in memory
- Calculations over entire arrays
- Easy and fast

**NumPy** is often used along with packages like **SciPy** (Scientific Python) and **Mat−plotlib** (plotting library). This combination is widely used as a replacement for MatLab, a popular platform for technical computing. However, Python alternative to MatLab is now seen as a more modern and complete programming language.
It is open source, which is an added advantage of NumPy.

![Picture title](Recursos/Numpy.png)

## 1.1. 1D arrays
### Numpy array creation
Like lists, arrays are collections of items, but of the same type (e.g., all numbers or all strings). To create and use arrays in Python, you need use the previously imported library `numpy`.


In [5]:
# Create an array from scratch
my_array = np.array([-10, 30, 60, 90, 120, 150, -100])
print(my_array)

[ -10   30   60   90  120  150 -100]


In [6]:
# Alternative options to create arrays from scratch
# Create an 1D array of integers from one to ten using arange
print('Alternative 1:', np.arange(1, 11))

# Create a 2x4 array with numbers between (0,1) using random
print('Alternative 2:', np.random.random((2, 4)))

Alternative 1: [ 1  2  3  4  5  6  7  8  9 10]
Alternative 2: [[0.83131076 0.04359541 0.22171181 0.57828331]
 [0.17080531 0.4333413  0.11809281 0.21314899]]


In [96]:
# Transform the lists height and weight into numpy arrays
np_height = np.array(height)
print(type(np_height),np_height)
np_weight = np.array(weight)
print(type(np_weight), np_weight)
np_height

<class 'numpy.ndarray'> [1.73 1.68 1.71 1.89 1.79]
<class 'numpy.ndarray'> [65.4 59.2 63.6 88.4 68.7]


array([1.73, 1.68, 1.71, 1.89, 1.79])

In [10]:
# Numpy: remarks
np.array([1.0, "is", True])
# Numpy arrays: contain only one type

array(['1.0', 'is', 'True'], dtype='<U32')

### Subsetting and modifiying 1D Numpy arrays

In [4]:
# the following code will give an error
#bmi = weight / height ** 2

#How to solve it: Using numpy


In [97]:
bmi = np_weight / np_height ** 2
#bmi = np.array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [12]:
# Subsetting
# obtain the last element
bmi[-1]

21.44127836209856

In [13]:
#identify the values greather than 21


array([ True, False,  True,  True,  True])

In [14]:
# create the list bmiplus with the elements whose values greather than 21

bmiplus


array([21.85171573, 21.75028214, 24.7473475 , 21.44127836])

In [15]:
print(my_array)
my_array[0] = 0 # modify first element
my_array[-1] = 180 # modify last element
print(my_array)

[ -10   30   60   90  120  150 -100]
[  0  30  60  90 120 150 180]


In [16]:
my_array = np.(my_array,[240, 270, 300, 330, 360]) # append elements
print(my_array)

[  0  30  60  90 120 150 180 240 270 300 330 360]


In [17]:
my_array = np.(my_array,7,210) # insert element at index 7
print(my_array) 

[  0  30  60  90 120 150 180 210 240 270 300 330 360]


In [18]:
my_array = np.(my_array,-1) # delete last element
print(my_array)

[  0  30  60  90 120 150 180 210 240 270 300 330]


### Operations with 1D arrays

In [98]:
print('number of elements in array =', my_array.shape[0]) # the [0] retrieves element 0 of shape

number of elements in array = 12


In [99]:
print('number of elements in array =', my_array.size) # print the number of elements in array

number of elements in array = 12


In [23]:
# Different types: different bevabour
print(height)
print(height + height) 
print(np_height)
print(np_height+np_height)

[1.73, 1.68, 1.71, 1.89, 1.79]
[1.73, 1.68, 1.71, 1.89, 1.79, 1.73, 1.68, 1.71, 1.89, 1.79]
[1.73 1.68 1.71 1.89 1.79]
[3.46 3.36 3.42 3.78 3.58]


## 1.2. 2D arrays

In [24]:
# create a 2D array 
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
[65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

### Subsetting and modifiying 2D Numpy arrays

In [100]:
# use the method shape for np_2d
print() #complete the code to print the array shape

![Picture title](Recursos/2Darray.png)

In [26]:
#get the first row of the array
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [27]:
# get the fourth element of the first row
np_2d[0,3]

1.89

In [28]:
# get from bot rows the first three elements
np_2d[:,0:3 ]

array([[ 1.73,  1.68,  1.71],
       [65.4 , 59.2 , 63.6 ]])

![Picture title](Recursos/SinFunction.png)

In [102]:
my_sines = np.sin(np.radians(my_array)) # compute the sine of the elements in my_array
print(np.round(my_sines,2)) # print the array with just two decimal places

[ 0.    0.5   0.87  1.    0.87  0.5   0.   -0.5  -0.87 -1.   -0.87 -0.5 ]


In [30]:
# create a 3 x 3 array
array_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [104]:
# array plus scalar


array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [105]:
print(array_a * 2) # array times scalar
print()
print(array_a / 2) # array divided by scalar
print()
print(array_a ** 2) # array elevated to the scalar

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [33]:
# Create another 3 x 3 array
array_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print() # element-wise sum the two arrays

[[10 10 10]
 [10 10 10]
 [10 10 10]]


### Comparison operators and Boolean arrays

Comparison operators also work on arrays. Suppose we have two arrays with the months of the year, and precipitation values in mm. Suppose we'd like to know the months with precipitation higher than 100 mm and their precipitation values. We can do the following:

In [36]:
months = np.array(['January', 'February', 'March', 'April', 'May', 'June', 
                   'July', 'August', 'September', 'October', 'November', 'December']) # array of months
precip = np.array([142, 89, 114, 74, 53, 38, 13, 25, 43, 109, 165, 137]) # monthly precipitation values in mm

high_precip = precip > 100 # Boolean array for monthly precipitation values more than 100 mm
low_precip = precip < 100

print(high_precip, '\n') # print Boolean array

print('Months with precipitation > 100 mm:', months[high_precip]) # print months with precipitation > 100 mm
print('Values of precipitation in these months:', precip[high_precip]) # print these months precipitation values

print('Months with precipitation = 100 mm:', months[low_precip]) # print months with precipitation < 100 mm
print('Values of precipitation in these months:', precip[low_precip]) # print these months precipitation values

[ True False  True False False False False False False  True  True  True] 

Months with precipitation > 100 mm: ['January' 'March' 'October' 'November' 'December']
Values of precipitation in these months: [142 114 109 165 137]
Months with precipitation = 100 mm: ['February' 'April' 'May' 'June' 'July' 'August' 'September']
Values of precipitation in these months: [89 74 53 38 13 25 43]


## 1.3. Basic Statistics

In [37]:
#Create random data
# np.ramdom.norma(distribution mean, distribution standar deviation, number of samples)
rd_height = np.round(np.random.normal(1.75, 0.20, 200), 2)
rd_weight = np.round(np.random.normal(60.32, 15, 200), 2)
np_city = np.column_stack((rd_height, rd_weight))
np_city

array([[ 2.01, 58.74],
       [ 1.89, 60.26],
       [ 1.54, 81.07],
       [ 1.6 , 47.65],
       [ 1.6 , 50.87],
       [ 2.06, 70.43],
       [ 1.34, 62.5 ],
       [ 1.95, 47.95],
       [ 1.74, 67.7 ],
       [ 1.96, 75.16],
       [ 1.82, 57.07],
       [ 1.99, 42.65],
       [ 1.6 , 53.46],
       [ 1.32, 60.79],
       [ 2.03, 53.69],
       [ 1.83, 61.  ],
       [ 1.58, 61.5 ],
       [ 1.54, 47.68],
       [ 1.71, 59.04],
       [ 2.05, 56.19],
       [ 1.83, 28.78],
       [ 1.74, 44.57],
       [ 1.95, 73.78],
       [ 1.57, 37.69],
       [ 1.76, 59.59],
       [ 1.86, 55.92],
       [ 1.82, 80.8 ],
       [ 1.97, 72.9 ],
       [ 1.58, 34.19],
       [ 1.49, 61.61],
       [ 1.81, 44.51],
       [ 1.63, 47.74],
       [ 1.96, 45.87],
       [ 1.89, 52.28],
       [ 1.37, 53.71],
       [ 1.25, 50.37],
       [ 1.78, 50.33],
       [ 1.95, 48.  ],
       [ 1.82, 70.64],
       [ 2.  , 37.  ],
       [ 1.71, 45.06],
       [ 1.95, 75.76],
       [ 1.8 , 35.07],
       [ 1.

In [38]:
# Get the mean of height
#Using basic operations
mean = np_city.sum(axis=0)/200 #/np_city.size
print(mean)

#using mean function
print(np.mean(np_city[:,0]))
print(np.mean(np_city[:,1]))

[ 1.74205 59.4416 ]
1.7420499999999999
59.4416


In [39]:
# Get the median of height
np.median(np_city[:,0])
# Get the standard deviation
np.std(np_city[:,0])

1.75

In [42]:
teachers_publications= np.array([[2,4,4],[0,2,4],[2,4,2],[3,1,3],[5,3,2]])
teachers_publications

array([[2, 4, 4],
       [0, 2, 4],
       [2, 4, 2],
       [3, 1, 3],
       [5, 3, 2]])

In [43]:
print(teachers_publications.sum(axis=0)) # cumulative publications by teacher
print(teachers_publications.sum(axis=1)) # cumulative publications by year

print(teachers_publications.min(axis=1)) # minimun number in the array by year
print(teachers_publications.max(axis=1)) # maximun number in the array by year

print(teachers_publications.min()) # minimun number in the array
print(teachers_publications.max()) # maximun number in the array

[12 14 15]
[10  6  8  7 10]
0
5
[2 0 2 1 2]
[4 4 4 3 5]


# Part 2. Pandas

## 2.1. Dataframes Methods and Attributes

Python objects have attributes and methods.
**Methods:** Unlike attributes, python methods have parenthesis.

To Insert a table with the main Pandas methods 

## 2.2. Import and Read Data

- Import data from:
    - CSV
    - XLSX
    - SQL

### 2.2.1. Import a CSV File
To import a csv file, we use the *read_csv* pandas's method.

In [44]:
# Import and read a csv file


Country ISO 3166-1 alpha-3  Year         Total          Coal  \
0      Afghanistan                AFG  1750      0.000000           NaN   
1      Afghanistan                AFG  1751      0.000000           NaN   
2      Afghanistan                AFG  1752      0.000000           NaN   
3      Afghanistan                AFG  1753      0.000000           NaN   
4      Afghanistan                AFG  1754      0.000000           NaN   
...            ...                ...   ...           ...           ...   
63099       Global                WLD  2017  36096.739276  14506.973805   
63100       Global                WLD  2018  36826.506600  14746.830688   
63101       Global                WLD  2019  37082.558969  14725.978025   
63102       Global                WLD  2020  35264.085734  14174.564010   
63103       Global                WLD  2021  37123.850352  14979.598083   

                Oil          Gas       Cement     Flaring       Other  \
0               NaN          NaN          NaN         NaN         NaN   
1               NaN          NaN          NaN         NaN         NaN   
2               NaN          NaN          NaN         NaN         NaN   
3               NaN          NaN          NaN         NaN         NaN   
4               NaN          NaN          NaN         NaN         NaN   
...             ...          ...          ...         ...         ...   
63099  12242.627935  7144.928128  1507.923185  391.992176  302.294047   
63100  12266.016285  7529.846784  1569.218392  412.115746  302.478706   
63101  12345.653374  7647.528220  1617.506786  439.253991  306.638573   
63102  11191.808551  7556.290283  1637.537532  407.583673  296.301685   
63103  11837.159116  7921.829472  1672.592372  416.525563  296.145746   

       Per Capita  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
...           ...  
63099    4.749682  
63100    4.792753  
63101    4.775633  
63102    4.497423  
63103    4.693699  

[63104 rows x 11 columns]

### 2.2.2. Import a xlsx File
To import a xlsx file, we use the *read_excel* method.

In [45]:
# Convert csv file to xlsx file
!pip install openpyxl
#df1.to_excel("Datos/CO2Emissions.xlsx")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 KB 29.7 MB/s eta 0:00:00
You should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.


In [46]:
# Import and read a xlsx file


Unnamed: 0      Country ISO 3166-1 alpha-3  Year         Total  \
0               0  Afghanistan                AFG  1750      0.000000   
1               1  Afghanistan                AFG  1751      0.000000   
2               2  Afghanistan                AFG  1752      0.000000   
3               3  Afghanistan                AFG  1753      0.000000   
4               4  Afghanistan                AFG  1754      0.000000   
...           ...          ...                ...   ...           ...   
63099       63099       Global                WLD  2017  36096.739276   
63100       63100       Global                WLD  2018  36826.506600   
63101       63101       Global                WLD  2019  37082.558969   
63102       63102       Global                WLD  2020  35264.085734   
63103       63103       Global                WLD  2021  37123.850352   

               Coal           Oil          Gas       Cement     Flaring  \
0               NaN           NaN          NaN          NaN         NaN   
1               NaN           NaN          NaN          NaN         NaN   
2               NaN           NaN          NaN          NaN         NaN   
3               NaN           NaN          NaN          NaN         NaN   
4               NaN           NaN          NaN          NaN         NaN   
...             ...           ...          ...          ...         ...   
63099  14506.973805  12242.627935  7144.928128  1507.923185  391.992176   
63100  14746.830688  12266.016285  7529.846784  1569.218392  412.115746   
63101  14725.978025  12345.653374  7647.528220  1617.506786  439.253991   
63102  14174.564010  11191.808551  7556.290283  1637.537532  407.583673   
63103  14979.598083  11837.159116  7921.829472  1672.592372  416.525563   

            Other  Per Capita  
0             NaN         NaN  
1             NaN         NaN  
2             NaN         NaN  
3             NaN         NaN  
4             NaN         NaN  
...           ...         ...  
63099  302.294047    4.749682  
63100  302.478706    4.792753  
63101  306.638573    4.775633  
63102  296.301685    4.497423  
63103  296.145746    4.693699  

[63104 rows x 12 columns]

### 2.2.3. Import Data from Database
To import tables from a database, we should use the **sqlaclhemy library** by calling its *create_engine* module.Then, we can use the *read_sql_query* pandas's method.

**SQLiteStudio:** https://sqlitestudio.pl/

In [47]:
# Import tables from a SQL Database

# Create a engine
engine=create_engine('sqlite:///Datos/CO2Emissions.db')


Country ISO 3166-1 alpha-3  Year Total Coal Oil Gas Cement Flaring  \
0  Afghanistan                AFG  1750     0                               
1  Afghanistan                AFG  1751     0                               
2  Afghanistan                AFG  1752     0                               
3  Afghanistan                AFG  1753     0                               
4  Afghanistan                AFG  1754     0                               

  Other Per Capita  
0                   
1                   
2                   
3                   
4

## 2.3. Explore Dataframes

- head method (To explore first 5 rows)
- dtypes attribute (To check data types)
- Other attributes: columns, ndim, size, shape, values
- Other methods: info(), describe(), median(), mean(), std(), max(), min()

In [48]:
# List first 5 records


Country ISO 3166-1 alpha-3  Year  Total  Coal  Oil  Gas  Cement  \
0  Afghanistan                AFG  1750    0.0   NaN  NaN  NaN     NaN   
1  Afghanistan                AFG  1751    0.0   NaN  NaN  NaN     NaN   
2  Afghanistan                AFG  1752    0.0   NaN  NaN  NaN     NaN   
3  Afghanistan                AFG  1753    0.0   NaN  NaN  NaN     NaN   
4  Afghanistan                AFG  1754    0.0   NaN  NaN  NaN     NaN   

   Flaring  Other  Per Capita  
0      NaN    NaN         NaN  
1      NaN    NaN         NaN  
2      NaN    NaN         NaN  
3      NaN    NaN         NaN  
4      NaN    NaN         NaN

In [49]:
# Check types for all columns
df1.dtypes

Country                object
ISO 3166-1 alpha-3     object
Year                    int64
Total                 float64
Coal                  float64
Oil                   float64
Gas                   float64
Cement                float64
Flaring               float64
Other                 float64
Per Capita            float64
dtype: object

In [50]:
# Show column names


Index(['Country', 'ISO 3166-1 alpha-3', 'Year', 'Total', 'Coal', 'Oil', 'Gas',
       'Cement', 'Flaring', 'Other', 'Per Capita'],
      dtype='object')

In [51]:
# Show dimension of dataframe


(63104, 11)

In [52]:
# Show summary of each column


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63104 entries, 0 to 63103
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Country             63104 non-null  object 
 1   ISO 3166-1 alpha-3  61472 non-null  object 
 2   Year                63104 non-null  int64  
 3   Total               62904 non-null  float64
 4   Coal                21744 non-null  float64
 5   Oil                 21717 non-null  float64
 6   Gas                 21618 non-null  float64
 7   Cement              20814 non-null  float64
 8   Flaring             21550 non-null  float64
 9   Other               1620 non-null   float64
 10  Per Capita          18974 non-null  float64
dtypes: float64(8), int64(1), object(2)
memory usage: 5.3+ MB


In [53]:
# Show descriptive statistics


Year         Total          Coal           Oil           Gas  \
count  63104.000000  62904.000000  21744.000000  21717.000000  21618.000000   
mean    1885.500000     55.224788     73.968916     55.760624     23.504285   
std       78.519728    824.845435    598.986992    519.034563    247.674772   
min     1750.000000      0.000000      0.000000      0.000000      0.000000   
25%     1817.750000      0.000000      0.000000      0.091600      0.000000   
50%     1885.500000      0.000000      0.271852      1.044240      0.000000   
75%     1953.250000      0.549342      6.736411      8.339752      0.581628   
max     2021.000000  37123.850352  15051.512770  12345.653374   7921.829472   

             Cement       Flaring        Other    Per Capita  
count  20814.000000  21550.000000  1620.000000  18974.000000  
mean       4.330443      1.712695    10.951389      4.413363  
std       50.305770     16.727067    39.034073     17.432815  
min        0.000000      0.000000     0.000000      0.000000  
25%        0.000000      0.000000     0.520885      0.197866  
50%        0.022756      0.000000     1.255329      1.303949  
75%        0.568502      0.000000     4.385471      5.077994  
max     1672.592372    439.253991   306.638573    834.192642

In [54]:
# Show min, max, mean, median, and std of a column
 # Min value of each column
print(" ") # White space
# Identify the min amount of CO2 Emissions from coal industry


Country       Afghanistan
Year                 1750
Total                 0.0
Coal                  0.0
Oil                   0.0
Gas                   0.0
Cement                0.0
Flaring               0.0
Other                 0.0
Per Capita            0.0
dtype: object
 
0.0


In [55]:
# Indentify the max amount of CO2 Emissions from coal


The max amount of CO2 from coal: 15051.51 Mt


## 2.4. Dataframe groupby Method

Using "group by" method we can:
- Split the data into groups based on some criteria
- Calculate statistics (or apply a function) to each group

In [56]:
# Group data using a categorical column



In [57]:
# Calculate mean value of CO2 emissions by country



Coal        Oil        Gas
Country                                                   
Afghanistan                 0.790089   1.802428   0.277625
Albania                     0.750357   2.088072   0.187722
Algeria                     1.108882  15.600961  20.324051
Andorra                     0.000000   0.483890   0.000000
Angola                      0.022233   4.817033   0.640445
...                              ...        ...        ...
Viet Nam                   17.438277  10.834602   2.387313
Wallis and Futuna Islands   0.000000   0.024157   0.000000
Yemen                       0.069130   8.265044   0.189377
Zambia                      1.665252   1.675202   0.000000
Zimbabwe                    5.265026   1.268349   0.000000

[232 rows x 3 columns]

In [58]:
# Show max CO2 emissions by year


Year          Coal           Oil          Gas
0    1750      9.350528      0.000000     0.000000
1    1751      9.350528      0.000000     0.000000
2    1752      9.354192      0.000000     0.000000
3    1753      9.354192      0.000000     0.000000
4    1754      9.357856      0.000000     0.000000
..    ...           ...           ...          ...
267  2017  14506.973805  12242.627935  7144.928128
268  2018  14746.830688  12266.016285  7529.846784
269  2019  14725.978025  12345.653374  7647.528220
270  2020  14174.564010  11191.808551  7556.290283
271  2021  14979.598083  11837.159116  7921.829472

[272 rows x 4 columns]

## 2.5. Dataframe: Filtering

To subset the data we can apply Boolean indexing. This indexing is commonly known as a filter.

In [59]:
# Show CO2 Emissions from Oil industry greater than 100 Mt



Country ISO 3166-1 alpha-3  Year         Total          Coal  \
3241   Australia                AUS  1999    343.488633    183.215379   
3242   Australia                AUS  2000    349.635487    185.781229   
3243   Australia                AUS  2001    357.132367    190.066589   
3244   Australia                AUS  2002    361.540810    191.131030   
3245   Australia                AUS  2003    369.279512    195.370417   
...          ...                ...   ...           ...           ...   
63099     Global                WLD  2017  36096.739276  14506.973805   
63100     Global                WLD  2018  36826.506600  14746.830688   
63101     Global                WLD  2019  37082.558969  14725.978025   
63102     Global                WLD  2020  35264.085734  14174.564010   
63103     Global                WLD  2021  37123.850352  14979.598083   

                Oil          Gas       Cement     Flaring       Other  \
3241     100.399487    45.548715     3.519991    7.165139    3.639921   
3242     102.337360    46.593883     3.620856    7.952858    3.349301   
3243     102.582541    49.310577     3.540903    8.172284    3.459474   
3244     104.516285    50.573495     3.487738    8.007496    3.824767   
3245     109.570680    49.701209     3.584016    7.157978    3.895211   
...             ...          ...          ...         ...         ...   
63099  12242.627935  7144.928128  1507.923185  391.992176  302.294047   
63100  12266.016285  7529.846784  1569.218392  412.115746  302.478706   
63101  12345.653374  7647.528220  1617.506786  439.253991  306.638573   
63102  11191.808551  7556.290283  1637.537532  407.583673  296.301685   
63103  11837.159116  7921.829472  1672.592372  416.525563  296.145746   

       Per Capita  
3241    18.269805  
3242    18.384487  
3243    18.554121  
3244    18.563550  
3245    18.746105  
...           ...  
63099    4.749682  
63100    4.792753  
63101    4.775633  
63102    4.497423  
63103    4.693699  

[1210 rows x 11 columns]

In [60]:
# CO2 Emissions From Oil and Gas industries greater than 100 Mt



Country  Year           Oil          Gas
9475   Canada  1977    233.700912   101.954464
9476   Canada  1978    233.823426   104.551318
9477   Canada  1979    244.293536   112.572736
9478   Canada  1980    241.294388   112.040529
9479   Canada  1981    227.908128   110.026256
...       ...   ...           ...          ...
63099  Global  2017  12242.627935  7144.928128
63100  Global  2018  12266.016285  7529.846784
63101  Global  2019  12345.653374  7647.528220
63102  Global  2020  11191.808551  7556.290283
63103  Global  2021  11837.159116  7921.829472

[539 rows x 4 columns]

In [61]:
# CO2 Ecuador's emissions after 2010



Country ISO 3166-1 alpha-3  Year      Total  Coal        Oil       Gas  \
16037  Ecuador                ECU  2011  37.398376   0.0  32.877072  1.047904   
16038  Ecuador                ECU  2012  37.408786   0.0  32.151600  1.399648   
16039  Ecuador                ECU  2013  39.654978   0.0  33.961616  1.590176   
16040  Ecuador                ECU  2014  43.731360   0.0  37.610960  1.630480   
16041  Ecuador                ECU  2015  41.275735   0.0  35.442329  1.535077   
16042  Ecuador                ECU  2016  40.177794   0.0  34.295040  1.656128   
16043  Ecuador                ECU  2017  40.075534   0.0  34.284503  1.538736   
16044  Ecuador                ECU  2018  38.245122   0.0  32.983328  1.359344   
16045  Ecuador                ECU  2019  40.264468   0.0  34.851520  1.212896   
16046  Ecuador                ECU  2020  34.457458   0.0  29.006557  1.030269   
16047  Ecuador                ECU  2021  41.321734   0.0  35.500845  1.026362   

         Cement   Flaring  Other  Per Capita  
16037  2.238632  1.234768    NaN    2.454328  
16038  2.353350  1.504188    NaN    2.415982  
16039  2.612421  1.490765    NaN    2.522102  
16040  2.602494  1.887426    NaN    2.740405  
16041  2.310700  1.987630    NaN    2.548530  
16042  2.188461  2.038164    NaN    2.443966  
16043  2.243666  2.008630    NaN    2.400172  
16044  2.271268  1.631182    NaN    2.247641  
16045  2.472370  1.727682    NaN    2.321556  
16046  2.472370  1.948263    NaN    1.959080  
16047  2.472370  2.322157    NaN    2.321741

## 2.6. Dataframe: Slicing

There are a number of ways to subset the Data Frame:
- One or more columns
- One or more rows
- A subset of rows and columns
- Using iloc an loc methods


Rows and columns can be selected by their position or label

When selecting one column, it is possible to use single set of brackets, but the resulting object will be a Series (not a DataFrame):

In [62]:
# Select one column


0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
            ...     
63099    1507.923185
63100    1569.218392
63101    1617.506786
63102    1637.537532
63103    1672.592372
Name: Cement, Length: 63104, dtype: float64

When we need to select more than one column and/or make the output to be a DataFrame, we should use double brackets:

In [63]:
# Select many columns


Country  Year           Oil
0      Afghanistan  1750           NaN
1      Afghanistan  1751           NaN
2      Afghanistan  1752           NaN
3      Afghanistan  1753           NaN
4      Afghanistan  1754           NaN
...            ...   ...           ...
63099       Global  2017  12242.627935
63100       Global  2018  12266.016285
63101       Global  2019  12345.653374
63102       Global  2020  11191.808551
63103       Global  2021  11837.159116

[63104 rows x 3 columns]

If we need to select a range of rows, we can specify the range using ":"

In [64]:
# Selecting rows by their position



Country ISO 3166-1 alpha-3  Year  Total  Coal  Oil  Gas  Cement  \
0   Afghanistan                AFG  1750    0.0   NaN  NaN  NaN     NaN   
1   Afghanistan                AFG  1751    0.0   NaN  NaN  NaN     NaN   
2   Afghanistan                AFG  1752    0.0   NaN  NaN  NaN     NaN   
3   Afghanistan                AFG  1753    0.0   NaN  NaN  NaN     NaN   
4   Afghanistan                AFG  1754    0.0   NaN  NaN  NaN     NaN   
5   Afghanistan                AFG  1755    0.0   NaN  NaN  NaN     NaN   
6   Afghanistan                AFG  1756    0.0   NaN  NaN  NaN     NaN   
7   Afghanistan                AFG  1757    0.0   NaN  NaN  NaN     NaN   
8   Afghanistan                AFG  1758    0.0   NaN  NaN  NaN     NaN   
9   Afghanistan                AFG  1759    0.0   NaN  NaN  NaN     NaN   
10  Afghanistan                AFG  1760    0.0   NaN  NaN  NaN     NaN   
11  Afghanistan                AFG  1761    0.0   NaN  NaN  NaN     NaN   
12  Afghanistan                AFG  1762    0.0   NaN  NaN  NaN     NaN   
13  Afghanistan                AFG  1763    0.0   NaN  NaN  NaN     NaN   
14  Afghanistan                AFG  1764    0.0   NaN  NaN  NaN     NaN   
15  Afghanistan                AFG  1765    0.0   NaN  NaN  NaN     NaN   
16  Afghanistan                AFG  1766    0.0   NaN  NaN  NaN     NaN   
17  Afghanistan                AFG  1767    0.0   NaN  NaN  NaN     NaN   
18  Afghanistan                AFG  1768    0.0   NaN  NaN  NaN     NaN   
19  Afghanistan                AFG  1769    0.0   NaN  NaN  NaN     NaN   

    Flaring  Other  Per Capita  
0       NaN    NaN         NaN  
1       NaN    NaN         NaN  
2       NaN    NaN         NaN  
3       NaN    NaN         NaN  
4       NaN    NaN         NaN  
5       NaN    NaN         NaN  
6       NaN    NaN         NaN  
7       NaN    NaN         NaN  
8       NaN    NaN         NaN  
9       NaN    NaN         NaN  
10      NaN    NaN         NaN  
11      NaN    NaN         NaN  
12      NaN    NaN         NaN  
13      NaN    NaN         NaN  
14      NaN    NaN         NaN  
15      NaN    NaN         NaN  
16      NaN    NaN         NaN  
17      NaN    NaN         NaN  
18      NaN    NaN         NaN  
19      NaN    NaN         NaN

**Notice that the first row has a position 0, and the last value in the range is omitted: So for 0:20 range the first 20 rows are returned with the positions starting with 0 and ending with 19.**

In [65]:
# Selecting rows and columns using loc method


Country  Year  Oil
0   Afghanistan  1750  NaN
1   Afghanistan  1751  NaN
2   Afghanistan  1752  NaN
3   Afghanistan  1753  NaN
4   Afghanistan  1754  NaN
5   Afghanistan  1755  NaN
6   Afghanistan  1756  NaN
7   Afghanistan  1757  NaN
8   Afghanistan  1758  NaN
9   Afghanistan  1759  NaN
10  Afghanistan  1760  NaN

In [66]:
# Selecting rows and columns using iloc method



Country  Year  Oil
0  Afghanistan  1750  NaN
1  Afghanistan  1751  NaN
2  Afghanistan  1752  NaN
3  Afghanistan  1753  NaN
4  Afghanistan  1754  NaN
5  Afghanistan  1755  NaN
6  Afghanistan  1756  NaN
7  Afghanistan  1757  NaN
8  Afghanistan  1758  NaN
9  Afghanistan  1759  NaN

In [67]:
# Other Examples
display(df1.iloc[-1]) # Last row
display(df1.iloc[0:2, :]) # Two row and all columns
display(df1.iloc[:, 0]) # All rows and first column

Country                     Global
ISO 3166-1 alpha-3             WLD
Year                          2021
Total                 37123.850352
Coal                  14979.598083
Oil                   11837.159116
Gas                    7921.829472
Cement                 1672.592372
Flaring                 416.525563
Other                   296.145746
Per Capita                4.693699
Name: 63103, dtype: object

Country ISO 3166-1 alpha-3  Year  Total  Coal  Oil  Gas  Cement  \
0  Afghanistan                AFG  1750    0.0   NaN  NaN  NaN     NaN   
1  Afghanistan                AFG  1751    0.0   NaN  NaN  NaN     NaN   

   Flaring  Other  Per Capita  
0      NaN    NaN         NaN  
1      NaN    NaN         NaN

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...     
63099         Global
63100         Global
63101         Global
63102         Global
63103         Global
Name: Country, Length: 63104, dtype: object

## 2.7. Sorting Dataframes

We can sort the data by a value in the column. By default the sorting will occur in ascending order and a new data frame is return. It is important to use the **sort_values() method.**

In [68]:
# Create a new data frame from the original sorted by a column


Country ISO 3166-1 alpha-3  Year  Total  Coal  Oil  Gas  \
0           Afghanistan                AFG  1750    0.0   NaN  NaN  NaN   
42704  Papua New Guinea                PNG  1750    0.0   NaN  NaN  NaN   
42976          Paraguay                PRY  1750    0.0   NaN  NaN  NaN   
43248              Peru                PER  1750    0.0   NaN  NaN  NaN   
43520       Philippines                PHL  1750    0.0   NaN  NaN  NaN   

       Cement  Flaring  Other  Per Capita  
0         NaN      NaN    NaN         NaN  
42704     0.0      NaN    NaN         NaN  
42976     NaN      NaN    NaN         NaN  
43248     NaN      NaN    NaN         NaN  
43520     NaN      NaN    NaN         NaN

In [69]:
# Sorting by two or more columns


Country ISO 3166-1 alpha-3  Year      Total      Coal       Oil  \
0      Afghanistan                AFG  1750   0.000000       NaN       NaN   
1      Afghanistan                AFG  1751   0.000000       NaN       NaN   
2      Afghanistan                AFG  1752   0.000000       NaN       NaN   
3      Afghanistan                AFG  1753   0.000000       NaN       NaN   
4      Afghanistan                AFG  1754   0.000000       NaN       NaN   
...            ...                ...   ...        ...       ...       ...   
62555     Zimbabwe                ZWE  2017   9.596071  5.900452  3.226752   
62556     Zimbabwe                ZWE  2018  11.795478  7.177776  4.059712   
62557     Zimbabwe                ZWE  2019  11.114607  6.888320  3.656672   
62558     Zimbabwe                ZWE  2020  10.607897  6.721571  3.316712   
62559     Zimbabwe                ZWE  2021  11.296114  7.225620  3.500879   

       Gas    Cement  Flaring  Other  Per Capita  
0      NaN       NaN      NaN    NaN         NaN  
1      NaN       NaN      NaN    NaN         NaN  
2      NaN       NaN      NaN    NaN         NaN  
3      NaN       NaN      NaN    NaN         NaN  
4      NaN       NaN      NaN    NaN         NaN  
...    ...       ...      ...    ...         ...  
62555  0.0  0.468867      0.0    NaN    0.650533  
62556  0.0  0.557990      0.0    NaN    0.783639  
62557  0.0  0.569615      0.0    NaN    0.723861  
62558  0.0  0.569615      0.0    NaN    0.676970  
62559  0.0  0.569615      0.0    NaN    0.706293  

[63104 rows x 11 columns]

## 2.8. Handling Missing Values

Missing values are marked as NaN. There are number of methods to deal with missing values in the dataframe.

- If all values are missing, the sum will be equal to NaN
- Many descriptive statistics methods have skipnaoption to control if missing

### 2.8.1. Summary

In [70]:
# Show columns that have missing values


Country                   0
ISO 3166-1 alpha-3     1632
Year                      0
Total                   200
Coal                  41360
Oil                   41387
Gas                   41486
Cement                42290
Flaring               41554
Other                 61484
Per Capita            44130
dtype: int64

### 2.8.2. Methods to deal with missing values

![img2](Recursos/missing _val_methods.PNG)

In [71]:
# Example with dropna()


Country ISO 3166-1 alpha-3  Year         Total          Coal  \
3232   Australia                AUS  1990    278.154156    141.879819   
3233   Australia                AUS  1991    279.528510    146.082840   
3234   Australia                AUS  1992    284.525345    150.051381   
3235   Australia                AUS  1993    288.870537    150.098575   
3236   Australia                AUS  1994    293.696553    151.376241   
...          ...                ...   ...           ...           ...   
63099     Global                WLD  2017  36096.739276  14506.973805   
63100     Global                WLD  2018  36826.506600  14746.830688   
63101     Global                WLD  2019  37082.558969  14725.978025   
63102     Global                WLD  2020  35264.085734  14174.564010   
63103     Global                WLD  2021  37123.850352  14979.598083   

                Oil          Gas       Cement     Flaring       Other  \
3232      88.842090    34.454816     3.462872    7.272496    2.242063   
3233      88.245572    32.786243     3.183033    7.001201    2.229622   
3234      87.916828    33.970472     2.923411    7.303701    2.359551   
3235      90.386578    35.670002     3.004698    7.136743    2.573941   
3236      91.924087    37.032005     3.484276    6.880148    2.999795   
...             ...          ...          ...         ...         ...   
63099  12242.627935  7144.928128  1507.923185  391.992176  302.294047   
63100  12266.016285  7529.846784  1569.218392  412.115746  302.478706   
63101  12345.653374  7647.528220  1617.506786  439.253991  306.638573   
63102  11191.808551  7556.290283  1637.537532  407.583673  296.301685   
63103  11837.159116  7921.829472  1672.592372  416.525563  296.145746   

       Per Capita  
3232    16.315938  
3233    16.184767  
3234    16.293502  
3235    16.383765  
3236    16.494706  
...           ...  
63099    4.749682  
63100    4.792753  
63101    4.775633  
63102    4.497423  
63103    4.693699  

[1619 rows x 11 columns]

In [72]:
# Example with fillna()


Country ISO 3166-1 alpha-3  Year         Total          Coal  \
0      Afghanistan                AFG  1750      0.000000      0.000000   
1      Afghanistan                AFG  1751      0.000000      0.000000   
2      Afghanistan                AFG  1752      0.000000      0.000000   
3      Afghanistan                AFG  1753      0.000000      0.000000   
4      Afghanistan                AFG  1754      0.000000      0.000000   
...            ...                ...   ...           ...           ...   
63099       Global                WLD  2017  36096.739276  14506.973805   
63100       Global                WLD  2018  36826.506600  14746.830688   
63101       Global                WLD  2019  37082.558969  14725.978025   
63102       Global                WLD  2020  35264.085734  14174.564010   
63103       Global                WLD  2021  37123.850352  14979.598083   

                Oil          Gas       Cement     Flaring       Other  \
0          0.000000     0.000000     0.000000    0.000000    0.000000   
1          0.000000     0.000000     0.000000    0.000000    0.000000   
2          0.000000     0.000000     0.000000    0.000000    0.000000   
3          0.000000     0.000000     0.000000    0.000000    0.000000   
4          0.000000     0.000000     0.000000    0.000000    0.000000   
...             ...          ...          ...         ...         ...   
63099  12242.627935  7144.928128  1507.923185  391.992176  302.294047   
63100  12266.016285  7529.846784  1569.218392  412.115746  302.478706   
63101  12345.653374  7647.528220  1617.506786  439.253991  306.638573   
63102  11191.808551  7556.290283  1637.537532  407.583673  296.301685   
63103  11837.159116  7921.829472  1672.592372  416.525563  296.145746   

       Per Capita  
0        0.000000  
1        0.000000  
2        0.000000  
3        0.000000  
4        0.000000  
...           ...  
63099    4.749682  
63100    4.792753  
63101    4.775633  
63102    4.497423  
63103    4.693699  

[63104 rows x 11 columns]

In [73]:
# Fill null values with ffill method



Country ISO 3166-1 alpha-3  Year         Total          Coal  \
0      Afghanistan                AFG  1750      0.000000           NaN   
1      Afghanistan                AFG  1751      0.000000           NaN   
2      Afghanistan                AFG  1752      0.000000           NaN   
3      Afghanistan                AFG  1753      0.000000           NaN   
4      Afghanistan                AFG  1754      0.000000           NaN   
...            ...                ...   ...           ...           ...   
63099       Global                WLD  2017  36096.739276  14506.973805   
63100       Global                WLD  2018  36826.506600  14746.830688   
63101       Global                WLD  2019  37082.558969  14725.978025   
63102       Global                WLD  2020  35264.085734  14174.564010   
63103       Global                WLD  2021  37123.850352  14979.598083   

                Oil          Gas       Cement     Flaring       Other  \
0               NaN          NaN          NaN         NaN         NaN   
1               NaN          NaN          NaN         NaN         NaN   
2               NaN          NaN          NaN         NaN         NaN   
3               NaN          NaN          NaN         NaN         NaN   
4               NaN          NaN          NaN         NaN         NaN   
...             ...          ...          ...         ...         ...   
63099  12242.627935  7144.928128  1507.923185  391.992176  302.294047   
63100  12266.016285  7529.846784  1569.218392  412.115746  302.478706   
63101  12345.653374  7647.528220  1617.506786  439.253991  306.638573   
63102  11191.808551  7556.290283  1637.537532  407.583673  296.301685   
63103  11837.159116  7921.829472  1672.592372  416.525563  296.145746   

       Per Capita  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
...           ...  
63099    4.749682  
63100    4.792753  
63101    4.775633  
63102    4.497423  
63103    4.693699  

[63104 rows x 11 columns]

In [74]:
# Fill missing values with mean column value



Country ISO 3166-1 alpha-3  Year         Total          Coal  \
0      Afghanistan                AFG  1750      0.000000     73.968916   
1      Afghanistan                AFG  1751      0.000000     73.968916   
2      Afghanistan                AFG  1752      0.000000     73.968916   
3      Afghanistan                AFG  1753      0.000000     73.968916   
4      Afghanistan                AFG  1754      0.000000     73.968916   
...            ...                ...   ...           ...           ...   
63099       Global                WLD  2017  36096.739276  14506.973805   
63100       Global                WLD  2018  36826.506600  14746.830688   
63101       Global                WLD  2019  37082.558969  14725.978025   
63102       Global                WLD  2020  35264.085734  14174.564010   
63103       Global                WLD  2021  37123.850352  14979.598083   

                Oil          Gas       Cement     Flaring       Other  \
0         55.760624    23.504285     4.330443    1.712695   10.951389   
1         55.760624    23.504285     4.330443    1.712695   10.951389   
2         55.760624    23.504285     4.330443    1.712695   10.951389   
3         55.760624    23.504285     4.330443    1.712695   10.951389   
4         55.760624    23.504285     4.330443    1.712695   10.951389   
...             ...          ...          ...         ...         ...   
63099  12242.627935  7144.928128  1507.923185  391.992176  302.294047   
63100  12266.016285  7529.846784  1569.218392  412.115746  302.478706   
63101  12345.653374  7647.528220  1617.506786  439.253991  306.638573   
63102  11191.808551  7556.290283  1637.537532  407.583673  296.301685   
63103  11837.159116  7921.829472  1672.592372  416.525563  296.145746   

       Per Capita  
0        4.413363  
1        4.413363  
2        4.413363  
3        4.413363  
4        4.413363  
...           ...  
63099    4.749682  
63100    4.792753  
63101    4.775633  
63102    4.497423  
63103    4.693699  

[63104 rows x 11 columns]

## 2.9. Merge Dataframes

In [75]:
# Create new dataframes

prof_p = pd.DataFrame({"id":["E90", "E87"], "Name": ["Jorge", "Freddy"]})
display(prof_p)

prof_c = pd.DataFrame({"id":["E22", "E74", "E90"], "Name": ["Andrés", "Nadia", "Jorge"]})
display(prof_c)

address = pd.DataFrame({"id":["E87", "E22", "E49"],
                        "City":["Guayaquil", "Quito", "Cuenca"],
                        "Province":["Guayas", "Pichincha", "Azuay"]})
display(address)


id    Name
0  E90   Jorge
1  E87  Freddy

id    Name
0  E22  Andrés
1  E74   Nadia
2  E90   Jorge

id       City   Province
0  E87  Guayaquil     Guayas
1  E22      Quito  Pichincha
2  E49     Cuenca      Azuay

In [76]:
# Concat dataframes using concat



id    Name
0  E90   Jorge
1  E87  Freddy
0  E22  Andrés
1  E74   Nadia
2  E90   Jorge

In [77]:
# Concat dataframes using concat and ignoring index



id    Name
0  E90   Jorge
1  E87  Freddy
2  E22  Andrés
3  E74   Nadia
4  E90   Jorge

In [78]:
# Check for duplicates after concatenation



id   Name
4  E90  Jorge

In [79]:
# Remove duplicates


id    Name
1  E87  Freddy
2  E22  Andrés
3  E74   Nadia
4  E90   Jorge

In [80]:
# Order index



id    Name
0  E87  Freddy
1  E22  Andrés
2  E74   Nadia
3  E90   Jorge

In [81]:
# show professor and address dataframes



id    Name
0  E87  Freddy
1  E22  Andrés
2  E74   Nadia
3  E90   Jorge

id       City   Province
0  E87  Guayaquil     Guayas
1  E22      Quito  Pichincha
2  E49     Cuenca      Azuay

### 2.9.1. Inner join

In [82]:
# Merge dataframes (professors, address) by Inner Join

r

id    Name       City   Province
0  E87  Freddy  Guayaquil     Guayas
1  E22  Andrés      Quito  Pichincha


### 2.9.2. Left Outer Join

In [83]:
# Merge dataframes (professor, address) by Left Outer Join



id    Name       City   Province
0  E87  Freddy  Guayaquil     Guayas
1  E22  Andrés      Quito  Pichincha
2  E74   Nadia        NaN        NaN
3  E90   Jorge        NaN        NaN


### 2.9.3. Right Outer Join

In [84]:
# Merge dataframes (professor, address) by Right Outer Join



id    Name       City   Province
0  E87  Freddy  Guayaquil     Guayas
1  E22  Andrés      Quito  Pichincha
2  E49     NaN     Cuenca      Azuay

### 2.9.4. Full Outer Join

In [85]:
# Merge dataframes by Full Outer Join



id    Name       City   Province
0  E87  Freddy  Guayaquil     Guayas
1  E22  Andrés      Quito  Pichincha
2  E74   Nadia        NaN        NaN
3  E90   Jorge        NaN        NaN
4  E49     NaN     Cuenca      Azuay

## Test Part 2

Analyse and clean the following dataset by doing the tasks below:

- Import and read the excel file Capacitación FICT ABRIL - 2023.
- Show the summary of this dataset.
- Rename some columns.
- Drop unnecessary columns.
- Change "x" to registered and null values to unregistered.
- Show the amount of people registered in at least two courses (*use value_counts method*).
- Convert to only one column all the courses (*use melt method*).
- Show people registered in GIS Course.
- Save the final dataframe as a csv file named FICT_Courses into the Día2/Datos directory

In [86]:
# Import data from FICT Courses



Marca temporal Dirección de correo electrónico  \
0  2023-03-31 13:51:37.715           cgoyburo@espol.edu.ec   
1  2023-03-31 13:55:33.574           dvelaste@espol.edu.ec   
2  2023-03-31 13:55:34.843               dpaz@espol.edu.ec   
3  2023-03-31 13:58:01.143           nlagasca@espol.edu.ec   
4  2023-03-31 13:58:17.832           fetorres@espol.edu.ec   
5  2023-03-31 13:58:24.426             mmulas@espol.edu.ec   
6  2023-03-31 14:00:45.818            ogarces@espol.edu.ec   
7  2023-03-31 14:03:05.350           pestolay@espol.edu.ec   
8  2023-03-31 14:03:53.063           fpcarrio@espol.edu.ec   
9  2023-03-31 14:09:00.103           angnmedi@espol.edu.ec   
10 2023-03-31 14:11:46.495           juaedcag@espol.edu.ec   
11 2023-03-31 14:16:34.617           mogasant@espol.edu.ec   
12 2023-03-31 14:19:05.046           nlgarcia@espol.edu.ec   
13 2023-03-31 14:24:20.435           karmavil@espol.edu.ec   
14 2023-03-31 14:42:13.097           mogasant@espol.edu.ec   
15 2023-03-31 15:12:06.999           dandrade@espol.edu.ec   
16 2023-03-31 15:19:08.176           kenjduen@espol.edu.ec   
17 2023-03-31 15:20:50.073            mgilces@espol.edu.ec   
18 2023-03-31 15:34:55.688           ecolmont@espol.edu.ec   
19 2023-03-31 15:40:38.343           gialpena@espol.edu.ec   
20 2023-03-31 15:59:55.549           aavaldiv@espol.edu.ec   
21 2023-03-31 19:03:57.718            pvilela@espol.edu.ec   
22 2023-03-31 19:09:53.913            kftello@espol.edu.ec   
23 2023-04-01 08:29:58.851           jonimend@espol.edu.ec   
24 2023-04-02 18:07:40.232           pacampov@espol.edu.ec   
25 2023-04-03 11:24:27.692           mirlopez@espol.edu.ec   
26 2023-04-03 11:46:09.440           anjeclav@espol.edu.ec   
27 2023-04-03 12:23:26.419           mivavill@espol.edu.ec   
28 2023-04-03 13:58:54.179           mayelord@espol.edu.ec   
29 2023-04-03 16:15:56.749           daanarce@espol.edu.ec   
30 2023-04-03 18:09:24.095           sebasuar@espol.edu.ec   
31 2023-04-04 12:24:43.980           darialta@espol.edu.ec   
32 2023-04-04 14:08:02.003            jrreyes@espol.edu.ec   
33 2023-04-04 14:09:15.138           Jsmendoz@espol.edu.ec   
34 2023-04-04 14:09:16.769           aeguzman@espol.edu.ec   
35 2023-04-04 14:10:32.072           jolizamb@espol.edu.ec   
36 2023-04-04 14:11:00.885            fsagnay@espol.edu.ec   
37 2023-04-04 14:12:58.573            rsayala@espol.edu.ec   
38 2023-04-04 14:22:03.034           kmmuthre@espol.edu.ec   
39 2023-04-04 14:25:35.116           dfalquez@espol.edu.ec   
40 2023-04-04 14:35:32.383          nancyvict593@gmail.com   
41 2023-04-04 15:15:00.054           pacampov@espol.edu.ec   
42 2023-04-04 15:18:20.388              olema@espol.edu.ec   
43 2023-04-04 16:06:06.836           chbustam@espol.edu.ec   
44 2023-04-04 16:12:09.213           luisanch@espol.edu.ec   
45 2023-04-04 16:13:34.684           cholmoli@espol.edu.ec   
46 2023-04-05 08:47:05.151           jabrione@espol.edu.ec   
47 2023-04-05 09:54:17.241           mccastil@espol.edu.ec   
48 2023-04-05 11:13:08.102           mirlopez@espol.edu.ec   
49 2023-04-05 12:23:16.181           kataesco@espol.edu.ec   
50 2023-04-06 14:24:22.212           crsavazq@espol.edu.ec   
51 2023-04-06 14:26:15.914           whurtare@espol.edu.ec   

                         Nombres Completos Capacitaciones  AWC  \
0             Cindy Samanda Goyburo Chávez              x    x   
1                Andrés Velástegui Montoya            NaN    x   
2            Daniela Margarita Paz Barzola              x    x   
3               Nadia José Lagasca Loaiza               x    x   
4          Federico Ricardo Torres Negrete              x  NaN   
5                           Maurizio Mulas            NaN    x   
6                 Daniel Omar Garces Leon             NaN  NaN   
7                       Peter Olaya Carbo             NaN    x   
8            Freddy Paul Carrión Maldonado              x    x   
9                Angie Nicole Medina Toala              x    x   

In [87]:
# Data summary


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype         
---  ------                               --------------  -----         
 0   Marca temporal                       52 non-null     datetime64[ns]
 1   Dirección de correo electrónico      52 non-null     object        
 2   Nombres Completos                    52 non-null     object        
 3   Capacitaciones                       19 non-null     object        
 4   AWC                                  27 non-null     object        
 5   Bienestar Psicológico                24 non-null     object        
 6   Herramientas para Generar Bienestar  27 non-null     object        
 7   Python                               32 non-null     object        
 8   Unnamed: 8                           0 non-null      float64       
 9   Unnamed: 9                           0 non-null      float64       
dtypes: datetime64[ns

In [88]:
# Rename columns


Marca temporal                  Correo  \
0  2023-03-31 13:51:37.715   cgoyburo@espol.edu.ec   
1  2023-03-31 13:55:33.574   dvelaste@espol.edu.ec   
2  2023-03-31 13:55:34.843       dpaz@espol.edu.ec   
3  2023-03-31 13:58:01.143   nlagasca@espol.edu.ec   
4  2023-03-31 13:58:17.832   fetorres@espol.edu.ec   
5  2023-03-31 13:58:24.426     mmulas@espol.edu.ec   
6  2023-03-31 14:00:45.818    ogarces@espol.edu.ec   
7  2023-03-31 14:03:05.350   pestolay@espol.edu.ec   
8  2023-03-31 14:03:53.063   fpcarrio@espol.edu.ec   
9  2023-03-31 14:09:00.103   angnmedi@espol.edu.ec   
10 2023-03-31 14:11:46.495   juaedcag@espol.edu.ec   
11 2023-03-31 14:16:34.617   mogasant@espol.edu.ec   
12 2023-03-31 14:19:05.046   nlgarcia@espol.edu.ec   
13 2023-03-31 14:24:20.435   karmavil@espol.edu.ec   
14 2023-03-31 14:42:13.097   mogasant@espol.edu.ec   
15 2023-03-31 15:12:06.999   dandrade@espol.edu.ec   
16 2023-03-31 15:19:08.176   kenjduen@espol.edu.ec   
17 2023-03-31 15:20:50.073    mgilces@espol.edu.ec   
18 2023-03-31 15:34:55.688   ecolmont@espol.edu.ec   
19 2023-03-31 15:40:38.343   gialpena@espol.edu.ec   
20 2023-03-31 15:59:55.549   aavaldiv@espol.edu.ec   
21 2023-03-31 19:03:57.718    pvilela@espol.edu.ec   
22 2023-03-31 19:09:53.913    kftello@espol.edu.ec   
23 2023-04-01 08:29:58.851   jonimend@espol.edu.ec   
24 2023-04-02 18:07:40.232   pacampov@espol.edu.ec   
25 2023-04-03 11:24:27.692   mirlopez@espol.edu.ec   
26 2023-04-03 11:46:09.440   anjeclav@espol.edu.ec   
27 2023-04-03 12:23:26.419   mivavill@espol.edu.ec   
28 2023-04-03 13:58:54.179   mayelord@espol.edu.ec   
29 2023-04-03 16:15:56.749   daanarce@espol.edu.ec   
30 2023-04-03 18:09:24.095   sebasuar@espol.edu.ec   
31 2023-04-04 12:24:43.980   darialta@espol.edu.ec   
32 2023-04-04 14:08:02.003    jrreyes@espol.edu.ec   
33 2023-04-04 14:09:15.138   Jsmendoz@espol.edu.ec   
34 2023-04-04 14:09:16.769   aeguzman@espol.edu.ec   
35 2023-04-04 14:10:32.072   jolizamb@espol.edu.ec   
36 2023-04-04 14:11:00.885    fsagnay@espol.edu.ec   
37 2023-04-04 14:12:58.573    rsayala@espol.edu.ec   
38 2023-04-04 14:22:03.034   kmmuthre@espol.edu.ec   
39 2023-04-04 14:25:35.116   dfalquez@espol.edu.ec   
40 2023-04-04 14:35:32.383  nancyvict593@gmail.com   
41 2023-04-04 15:15:00.054   pacampov@espol.edu.ec   
42 2023-04-04 15:18:20.388      olema@espol.edu.ec   
43 2023-04-04 16:06:06.836   chbustam@espol.edu.ec   
44 2023-04-04 16:12:09.213   luisanch@espol.edu.ec   
45 2023-04-04 16:13:34.684   cholmoli@espol.edu.ec   
46 2023-04-05 08:47:05.151   jabrione@espol.edu.ec   
47 2023-04-05 09:54:17.241   mccastil@espol.edu.ec   
48 2023-04-05 11:13:08.102   mirlopez@espol.edu.ec   
49 2023-04-05 12:23:16.181   kataesco@espol.edu.ec   
50 2023-04-06 14:24:22.212   crsavazq@espol.edu.ec   
51 2023-04-06 14:26:15.914   whurtare@espol.edu.ec   

                                   Nombres  GIS  AWC Bienestar Psicológico  \
0             Cindy Samanda Goyburo Chávez    x    x                     x   
1                Andrés Velástegui Montoya  NaN    x                   NaN   
2            Daniela Margarita Paz Barzola    x    x                     x   
3               Nadia José Lagasca Loaiza     x    x                     x   
4          Federico Ricardo Torres Negrete    x  NaN                     x   
5                           Maurizio Mulas  NaN    x                     x   
6                 Daniel Omar Garces Leon   NaN  NaN                     x   
7                       Peter Olaya Carbo   NaN    x                     x   
8            Freddy Paul Carrión Maldonado    x    x                     x   
9                Angie Nicole Medina Toala    x    x                     x   
10             Juan Eduardo Caguana Amagua  NaN  NaN                     x   
11         Mónica Gabriela Santos Carrasco  NaN  NaN                     x   
12        Natividad Leonor Garcia Troncoso  NaN  NaN                   NaN   
13          Karla Maytee Villamar Marazita    x    x     

In [89]:
# Drop unnecessary columns



Correo                                 Nombres  GIS  AWC  \
0    cgoyburo@espol.edu.ec            Cindy Samanda Goyburo Chávez    x    x   
1    dvelaste@espol.edu.ec               Andrés Velástegui Montoya  NaN    x   
2        dpaz@espol.edu.ec           Daniela Margarita Paz Barzola    x    x   
3    nlagasca@espol.edu.ec              Nadia José Lagasca Loaiza     x    x   
4    fetorres@espol.edu.ec         Federico Ricardo Torres Negrete    x  NaN   
5      mmulas@espol.edu.ec                          Maurizio Mulas  NaN    x   
6     ogarces@espol.edu.ec                Daniel Omar Garces Leon   NaN  NaN   
7    pestolay@espol.edu.ec                      Peter Olaya Carbo   NaN    x   
8    fpcarrio@espol.edu.ec           Freddy Paul Carrión Maldonado    x    x   
9    angnmedi@espol.edu.ec               Angie Nicole Medina Toala    x    x   
10   juaedcag@espol.edu.ec             Juan Eduardo Caguana Amagua  NaN  NaN   
11   mogasant@espol.edu.ec         Mónica Gabriela Santos Carrasco  NaN  NaN   
12   nlgarcia@espol.edu.ec        Natividad Leonor Garcia Troncoso  NaN  NaN   
13   karmavil@espol.edu.ec          Karla Maytee Villamar Marazita    x    x   
14   mogasant@espol.edu.ec         Mónica Gabriela Santos Carrasco  NaN    x   
15   dandrade@espol.edu.ec            Deysi Albania Andrade Granda  NaN  NaN   
16   kenjduen@espol.edu.ec                      Jairo Dueñas Tovar    x  NaN   
17    mgilces@espol.edu.ec            Mary Joseph Gilces Cajamarca  NaN  NaN   
18   ecolmont@espol.edu.ec               Enrique Colmont Villacres  NaN    x   
19   gialpena@espol.edu.ec         Gina Alejandra Peña Villacreses    x    x   
20   aavaldiv@espol.edu.ec                  Angel Valdiviezo Ajila  NaN    x   
21    pvilela@espol.edu.ec  Paulina Elizabeth Vilela Govea, Ph. D.    x    x   
22    kftello@espol.edu.ec               Ken Francisco Tello Ayala  NaN    x   
23   jonimend@espol.edu.ec             Jonathan Israel Mendez Ruiz    x    x   
24   pacampov@espol.edu.ec          Paulo Andrés Campoverde Muñoz   NaN    x   
25   mirlopez@espol.edu.ec                    Mónica López Moncada  NaN  NaN   
26   anjeclav@espol.edu.ec              Angel Jesus Clavijo Rivera  NaN    x   
27   mivavill@espol.edu.ec     Michelle Vanessa Villacís Verdesoto  NaN  NaN   
28   mayelord@espol.edu.ec         Maylin Elizabeth Ordoñez Obando    x    x   
29   daanarce@espol.edu.ec       DANILO ANDRES ARCENTALES BASTIDAS  NaN  NaN   
30   sebasuar@espol.edu.ec          Sebastián Alonso Suárez Zamora  NaN  NaN   
31   darialta@espol.edu.ec          David Ricardo Altamirano Moran  NaN  NaN   
32    jrreyes@espol.edu.ec                              José Reyes    x  NaN   
33   Jsmendoz@espol.edu.ec                          Jorge Mendoza   NaN  NaN   
34   aeguzman@espol.edu.ec         ANDRÉS EDUARDO GUZMÁN VELÁSQUEZ  NaN    x   
35   jolizamb@espol.edu.ec     Johanna Lisseth Zambrano Anchundia     x  NaN   
36    fsagnay@espol.edu.ec                         Fernando Sagnay  NaN    x   
37    rsayala@espol.edu.ec                       René Ayala Lomas   NaN  NaN   
38   kmmuthre@espol.edu.ec                         Mishelle Muthre  NaN    x   
39   dfalquez@espol.edu.ec            Daniel Andrés Falquez Torres  NaN  NaN   
40  nancyvict593@gmail.com                             Nancy Zumba    x  NaN   
41   pacampov@espol.edu.ec           Paulo Andrés Campoverde Muñoz  NaN    x   
42      olema@espol.edu.ec                   Osmar G. Lema Caicedo    x    x   
43   chbustam@espol.edu.ec          Carlos Hugo Bustamante Torres     x  NaN   
44   luisanch@espol.edu.ec                   Luis Sanchez Calderon  NaN  NaN   
45   cholmoli@espol.edu.ec    MOLINA POW CHON LONG JOSUE ALEJANDRO  NaN  NaN   
46   jabrione@espol.edu.ec          Johnny Arián Briones Escalante    x  NaN   
47   mccastil@espol.edu.ec           María Cecibel Castillo Olvera  NaN    x   
48   mirlopez@espol.edu.ec                    Mónica López Moncada  NaN    x   
49   kataesco@espol.

In [90]:
# Change x values to registered



Correo                                 Nombres  \
0    cgoyburo@espol.edu.ec            Cindy Samanda Goyburo Chávez   
1    dvelaste@espol.edu.ec               Andrés Velástegui Montoya   
2        dpaz@espol.edu.ec           Daniela Margarita Paz Barzola   
3    nlagasca@espol.edu.ec              Nadia José Lagasca Loaiza    
4    fetorres@espol.edu.ec         Federico Ricardo Torres Negrete   
5      mmulas@espol.edu.ec                          Maurizio Mulas   
6     ogarces@espol.edu.ec                Daniel Omar Garces Leon    
7    pestolay@espol.edu.ec                      Peter Olaya Carbo    
8    fpcarrio@espol.edu.ec           Freddy Paul Carrión Maldonado   
9    angnmedi@espol.edu.ec               Angie Nicole Medina Toala   
10   juaedcag@espol.edu.ec             Juan Eduardo Caguana Amagua   
11   mogasant@espol.edu.ec         Mónica Gabriela Santos Carrasco   
12   nlgarcia@espol.edu.ec        Natividad Leonor Garcia Troncoso   
13   karmavil@espol.edu.ec          Karla Maytee Villamar Marazita   
14   mogasant@espol.edu.ec         Mónica Gabriela Santos Carrasco   
15   dandrade@espol.edu.ec            Deysi Albania Andrade Granda   
16   kenjduen@espol.edu.ec                      Jairo Dueñas Tovar   
17    mgilces@espol.edu.ec            Mary Joseph Gilces Cajamarca   
18   ecolmont@espol.edu.ec               Enrique Colmont Villacres   
19   gialpena@espol.edu.ec         Gina Alejandra Peña Villacreses   
20   aavaldiv@espol.edu.ec                  Angel Valdiviezo Ajila   
21    pvilela@espol.edu.ec  Paulina Elizabeth Vilela Govea, Ph. D.   
22    kftello@espol.edu.ec               Ken Francisco Tello Ayala   
23   jonimend@espol.edu.ec             Jonathan Israel Mendez Ruiz   
24   pacampov@espol.edu.ec          Paulo Andrés Campoverde Muñoz    
25   mirlopez@espol.edu.ec                    Mónica López Moncada   
26   anjeclav@espol.edu.ec              Angel Jesus Clavijo Rivera   
27   mivavill@espol.edu.ec     Michelle Vanessa Villacís Verdesoto   
28   mayelord@espol.edu.ec         Maylin Elizabeth Ordoñez Obando   
29   daanarce@espol.edu.ec       DANILO ANDRES ARCENTALES BASTIDAS   
30   sebasuar@espol.edu.ec          Sebastián Alonso Suárez Zamora   
31   darialta@espol.edu.ec          David Ricardo Altamirano Moran   
32    jrreyes@espol.edu.ec                              José Reyes   
33   Jsmendoz@espol.edu.ec                          Jorge Mendoza    
34   aeguzman@espol.edu.ec         ANDRÉS EDUARDO GUZMÁN VELÁSQUEZ   
35   jolizamb@espol.edu.ec     Johanna Lisseth Zambrano Anchundia    
36    fsagnay@espol.edu.ec                         Fernando Sagnay   
37    rsayala@espol.edu.ec                       René Ayala Lomas    
38   kmmuthre@espol.edu.ec                         Mishelle Muthre   
39   dfalquez@espol.edu.ec            Daniel Andrés Falquez Torres   
40  nancyvict593@gmail.com                             Nancy Zumba   
41   pacampov@espol.edu.ec           Paulo Andrés Campoverde Muñoz   
42      olema@espol.edu.ec                   Osmar G. Lema Caicedo   
43   chbustam@espol.edu.ec          Carlos Hugo Bustamante Torres    
44   luisanch@espol.edu.ec                   Luis Sanchez Calderon   
45   cholmoli@espol.edu.ec    MOLINA POW CHON LONG JOSUE ALEJANDRO   
46   jabrione@espol.edu.ec          Johnny Arián Briones Escalante   
47   mccastil@espol.edu.ec           María Cecibel Castillo Olvera   
48   mirlopez@espol.edu.ec                    Mónica López Moncada   
49   kataesco@espol.edu.ec      Katherine Tatiana Escobar Pesantes   
50   crsavazq@espol.edu.ec          CRISTIAN ALFONSO SALAS VÁZQUEZ   
51   whurtare@espol.edu.ec                  Walter Hurtares Orrala   

             GIS           AWC Bienestar Psicológico  \
0     registered    registered            registered   
1   unregistered    registered          unregistered   
2     registered    registered            registered   
3     registered    registered            registered   
4     registered  unregistere

In [91]:
# Show results from GIS Course


unregistered    33
registered      19
Name: GIS, dtype: int64

In [92]:
# Show results from Python Course


registered      32
unregistered    20
Name: Python, dtype: int64

In [93]:
# Convert to only one column all the courses



Nombres  Course        Answer
0          Cindy Samanda Goyburo Chávez     GIS    registered
1             Andrés Velástegui Montoya     GIS  unregistered
2         Daniela Margarita Paz Barzola     GIS    registered
3            Nadia José Lagasca Loaiza      GIS    registered
4       Federico Ricardo Torres Negrete     GIS    registered
..                                  ...     ...           ...
255       María Cecibel Castillo Olvera  Python    registered
256                Mónica López Moncada  Python  unregistered
257  Katherine Tatiana Escobar Pesantes  Python  unregistered
258      CRISTIAN ALFONSO SALAS VÁZQUEZ  Python    registered
259              Walter Hurtares Orrala  Python    registered

[260 rows x 3 columns]

In [94]:
# People registered in GIS Course


Nombres Course      Answer
0             Cindy Samanda Goyburo Chávez    GIS  registered
2            Daniela Margarita Paz Barzola    GIS  registered
3               Nadia José Lagasca Loaiza     GIS  registered
4          Federico Ricardo Torres Negrete    GIS  registered
8            Freddy Paul Carrión Maldonado    GIS  registered
9                Angie Nicole Medina Toala    GIS  registered
13          Karla Maytee Villamar Marazita    GIS  registered
16                      Jairo Dueñas Tovar    GIS  registered
19         Gina Alejandra Peña Villacreses    GIS  registered
21  Paulina Elizabeth Vilela Govea, Ph. D.    GIS  registered
23             Jonathan Israel Mendez Ruiz    GIS  registered
28         Maylin Elizabeth Ordoñez Obando    GIS  registered
32                              José Reyes    GIS  registered
35     Johanna Lisseth Zambrano Anchundia     GIS  registered
40                             Nancy Zumba    GIS  registered
42                   Osmar G. Lema Caicedo    GIS  registered
43          Carlos Hugo Bustamante Torres     GIS  registered
46          Johnny Arián Briones Escalante    GIS  registered
50          CRISTIAN ALFONSO SALAS VÁZQUEZ    GIS  registered

In [95]:
# Save dataframe as a csv file

